// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TaskSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskSummary{}

// TaskSummary Non-terminal tasks currently associated with a rack or tray.
type TaskSummary struct {
	// IDs of tasks in Waiting, Pending, or Running state, ordered by creation time and then task ID. Empty when no task is active. Rack summaries include component-scoped tasks on the rack; tray summaries include only tasks that explicitly target the tray.
	ActiveTaskIds []string `json:"activeTaskIds"`
}

type _TaskSummary TaskSummary

// NewTaskSummary instantiates a new TaskSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskSummary(activeTaskIds []string) *TaskSummary {
	this := TaskSummary{}
	this.ActiveTaskIds = activeTaskIds
	return &this
}

// NewTaskSummaryWithDefaults instantiates a new TaskSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskSummaryWithDefaults() *TaskSummary {
	this := TaskSummary{}
	return &this
}

// GetActiveTaskIds returns the ActiveTaskIds field value
func (o *TaskSummary) GetActiveTaskIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ActiveTaskIds
}

// GetActiveTaskIdsOk returns a tuple with the ActiveTaskIds field value
// and a boolean to check if the value has been set.
func (o *TaskSummary) GetActiveTaskIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActiveTaskIds, true
}

// SetActiveTaskIds sets field value
func (o *TaskSummary) SetActiveTaskIds(v []string) {
	o.ActiveTaskIds = v
}

func (o TaskSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["activeTaskIds"] = o.ActiveTaskIds
	return toSerialize, nil
}

func (o *TaskSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"activeTaskIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTaskSummary := _TaskSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varTaskSummary)

	if err != nil {
		return err
	}

	*o = TaskSummary(varTaskSummary)

	return err
}

type NullableTaskSummary struct {
	value *TaskSummary
	isSet bool
}

func (v NullableTaskSummary) Get() *TaskSummary {
	return v.value
}

func (v *NullableTaskSummary) Set(val *TaskSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskSummary(val *TaskSummary) *NullableTaskSummary {
	return &NullableTaskSummary{value: val, isSet: true}
}

func (v NullableTaskSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
