// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the TenantIdentityReencryptSecretsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantIdentityReencryptSecretsResponse{}

// TenantIdentityReencryptSecretsResponse Counters and per-field failures from a reencrypt run.
type TenantIdentityReencryptSecretsResponse struct {
	// Number of rows examined.
	RowsExamined *int32 `json:"rowsExamined,omitempty"`
	// Number of rows re-wrapped with the current key.
	RowsUpdated *int32 `json:"rowsUpdated,omitempty"`
	// Number of rows skipped because all fields were already on the target key.
	RowsSkippedAllOnTarget *int32 `json:"rowsSkippedAllOnTarget,omitempty"`
	// Number of individual fields re-wrapped.
	FieldsReencrypted *int32 `json:"fieldsReencrypted,omitempty"`
	// Number of fields skipped because they were already on the target key.
	FieldsSkippedOnTarget *int32 `json:"fieldsSkippedOnTarget,omitempty"`
	// Number of rows with at least one field that failed to re-wrap.
	RowsFailed *int32 `json:"rowsFailed,omitempty"`
	// Per-field re-wrap failures, when any occurred.
	Failures []TenantIdentityReencryptFailure `json:"failures,omitempty"`
	// Site machine_identity.current_encryption_key_id used as the re-wrap target.
	CurrentEncryptionKeyId *string `json:"currentEncryptionKeyId,omitempty"`
}

// NewTenantIdentityReencryptSecretsResponse instantiates a new TenantIdentityReencryptSecretsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantIdentityReencryptSecretsResponse() *TenantIdentityReencryptSecretsResponse {
	this := TenantIdentityReencryptSecretsResponse{}
	return &this
}

// NewTenantIdentityReencryptSecretsResponseWithDefaults instantiates a new TenantIdentityReencryptSecretsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantIdentityReencryptSecretsResponseWithDefaults() *TenantIdentityReencryptSecretsResponse {
	this := TenantIdentityReencryptSecretsResponse{}
	return &this
}

// GetRowsExamined returns the RowsExamined field value if set, zero value otherwise.
func (o *TenantIdentityReencryptSecretsResponse) GetRowsExamined() int32 {
	if o == nil || IsNil(o.RowsExamined) {
		var ret int32
		return ret
	}
	return *o.RowsExamined
}

// GetRowsExaminedOk returns a tuple with the RowsExamined field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsResponse) GetRowsExaminedOk() (*int32, bool) {
	if o == nil || IsNil(o.RowsExamined) {
		return nil, false
	}
	return o.RowsExamined, true
}

// HasRowsExamined returns a boolean if a field has been set.
func (o *TenantIdentityReencryptSecretsResponse) HasRowsExamined() bool {
	if o != nil && !IsNil(o.RowsExamined) {
		return true
	}

	return false
}

// SetRowsExamined gets a reference to the given int32 and assigns it to the RowsExamined field.
func (o *TenantIdentityReencryptSecretsResponse) SetRowsExamined(v int32) {
	o.RowsExamined = &v
}

// GetRowsUpdated returns the RowsUpdated field value if set, zero value otherwise.
func (o *TenantIdentityReencryptSecretsResponse) GetRowsUpdated() int32 {
	if o == nil || IsNil(o.RowsUpdated) {
		var ret int32
		return ret
	}
	return *o.RowsUpdated
}

// GetRowsUpdatedOk returns a tuple with the RowsUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsResponse) GetRowsUpdatedOk() (*int32, bool) {
	if o == nil || IsNil(o.RowsUpdated) {
		return nil, false
	}
	return o.RowsUpdated, true
}

// HasRowsUpdated returns a boolean if a field has been set.
func (o *TenantIdentityReencryptSecretsResponse) HasRowsUpdated() bool {
	if o != nil && !IsNil(o.RowsUpdated) {
		return true
	}

	return false
}

// SetRowsUpdated gets a reference to the given int32 and assigns it to the RowsUpdated field.
func (o *TenantIdentityReencryptSecretsResponse) SetRowsUpdated(v int32) {
	o.RowsUpdated = &v
}

// GetRowsSkippedAllOnTarget returns the RowsSkippedAllOnTarget field value if set, zero value otherwise.
func (o *TenantIdentityReencryptSecretsResponse) GetRowsSkippedAllOnTarget() int32 {
	if o == nil || IsNil(o.RowsSkippedAllOnTarget) {
		var ret int32
		return ret
	}
	return *o.RowsSkippedAllOnTarget
}

// GetRowsSkippedAllOnTargetOk returns a tuple with the RowsSkippedAllOnTarget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsResponse) GetRowsSkippedAllOnTargetOk() (*int32, bool) {
	if o == nil || IsNil(o.RowsSkippedAllOnTarget) {
		return nil, false
	}
	return o.RowsSkippedAllOnTarget, true
}

// HasRowsSkippedAllOnTarget returns a boolean if a field has been set.
func (o *TenantIdentityReencryptSecretsResponse) HasRowsSkippedAllOnTarget() bool {
	if o != nil && !IsNil(o.RowsSkippedAllOnTarget) {
		return true
	}

	return false
}

// SetRowsSkippedAllOnTarget gets a reference to the given int32 and assigns it to the RowsSkippedAllOnTarget field.
func (o *TenantIdentityReencryptSecretsResponse) SetRowsSkippedAllOnTarget(v int32) {
	o.RowsSkippedAllOnTarget = &v
}

// GetFieldsReencrypted returns the FieldsReencrypted field value if set, zero value otherwise.
func (o *TenantIdentityReencryptSecretsResponse) GetFieldsReencrypted() int32 {
	if o == nil || IsNil(o.FieldsReencrypted) {
		var ret int32
		return ret
	}
	return *o.FieldsReencrypted
}

// GetFieldsReencryptedOk returns a tuple with the FieldsReencrypted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsResponse) GetFieldsReencryptedOk() (*int32, bool) {
	if o == nil || IsNil(o.FieldsReencrypted) {
		return nil, false
	}
	return o.FieldsReencrypted, true
}

// HasFieldsReencrypted returns a boolean if a field has been set.
func (o *TenantIdentityReencryptSecretsResponse) HasFieldsReencrypted() bool {
	if o != nil && !IsNil(o.FieldsReencrypted) {
		return true
	}

	return false
}

// SetFieldsReencrypted gets a reference to the given int32 and assigns it to the FieldsReencrypted field.
func (o *TenantIdentityReencryptSecretsResponse) SetFieldsReencrypted(v int32) {
	o.FieldsReencrypted = &v
}

// GetFieldsSkippedOnTarget returns the FieldsSkippedOnTarget field value if set, zero value otherwise.
func (o *TenantIdentityReencryptSecretsResponse) GetFieldsSkippedOnTarget() int32 {
	if o == nil || IsNil(o.FieldsSkippedOnTarget) {
		var ret int32
		return ret
	}
	return *o.FieldsSkippedOnTarget
}

// GetFieldsSkippedOnTargetOk returns a tuple with the FieldsSkippedOnTarget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsResponse) GetFieldsSkippedOnTargetOk() (*int32, bool) {
	if o == nil || IsNil(o.FieldsSkippedOnTarget) {
		return nil, false
	}
	return o.FieldsSkippedOnTarget, true
}

// HasFieldsSkippedOnTarget returns a boolean if a field has been set.
func (o *TenantIdentityReencryptSecretsResponse) HasFieldsSkippedOnTarget() bool {
	if o != nil && !IsNil(o.FieldsSkippedOnTarget) {
		return true
	}

	return false
}

// SetFieldsSkippedOnTarget gets a reference to the given int32 and assigns it to the FieldsSkippedOnTarget field.
func (o *TenantIdentityReencryptSecretsResponse) SetFieldsSkippedOnTarget(v int32) {
	o.FieldsSkippedOnTarget = &v
}

// GetRowsFailed returns the RowsFailed field value if set, zero value otherwise.
func (o *TenantIdentityReencryptSecretsResponse) GetRowsFailed() int32 {
	if o == nil || IsNil(o.RowsFailed) {
		var ret int32
		return ret
	}
	return *o.RowsFailed
}

// GetRowsFailedOk returns a tuple with the RowsFailed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsResponse) GetRowsFailedOk() (*int32, bool) {
	if o == nil || IsNil(o.RowsFailed) {
		return nil, false
	}
	return o.RowsFailed, true
}

// HasRowsFailed returns a boolean if a field has been set.
func (o *TenantIdentityReencryptSecretsResponse) HasRowsFailed() bool {
	if o != nil && !IsNil(o.RowsFailed) {
		return true
	}

	return false
}

// SetRowsFailed gets a reference to the given int32 and assigns it to the RowsFailed field.
func (o *TenantIdentityReencryptSecretsResponse) SetRowsFailed(v int32) {
	o.RowsFailed = &v
}

// GetFailures returns the Failures field value if set, zero value otherwise.
func (o *TenantIdentityReencryptSecretsResponse) GetFailures() []TenantIdentityReencryptFailure {
	if o == nil || IsNil(o.Failures) {
		var ret []TenantIdentityReencryptFailure
		return ret
	}
	return o.Failures
}

// GetFailuresOk returns a tuple with the Failures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsResponse) GetFailuresOk() ([]TenantIdentityReencryptFailure, bool) {
	if o == nil || IsNil(o.Failures) {
		return nil, false
	}
	return o.Failures, true
}

// HasFailures returns a boolean if a field has been set.
func (o *TenantIdentityReencryptSecretsResponse) HasFailures() bool {
	if o != nil && !IsNil(o.Failures) {
		return true
	}

	return false
}

// SetFailures gets a reference to the given []TenantIdentityReencryptFailure and assigns it to the Failures field.
func (o *TenantIdentityReencryptSecretsResponse) SetFailures(v []TenantIdentityReencryptFailure) {
	o.Failures = v
}

// GetCurrentEncryptionKeyId returns the CurrentEncryptionKeyId field value if set, zero value otherwise.
func (o *TenantIdentityReencryptSecretsResponse) GetCurrentEncryptionKeyId() string {
	if o == nil || IsNil(o.CurrentEncryptionKeyId) {
		var ret string
		return ret
	}
	return *o.CurrentEncryptionKeyId
}

// GetCurrentEncryptionKeyIdOk returns a tuple with the CurrentEncryptionKeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsResponse) GetCurrentEncryptionKeyIdOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentEncryptionKeyId) {
		return nil, false
	}
	return o.CurrentEncryptionKeyId, true
}

// HasCurrentEncryptionKeyId returns a boolean if a field has been set.
func (o *TenantIdentityReencryptSecretsResponse) HasCurrentEncryptionKeyId() bool {
	if o != nil && !IsNil(o.CurrentEncryptionKeyId) {
		return true
	}

	return false
}

// SetCurrentEncryptionKeyId gets a reference to the given string and assigns it to the CurrentEncryptionKeyId field.
func (o *TenantIdentityReencryptSecretsResponse) SetCurrentEncryptionKeyId(v string) {
	o.CurrentEncryptionKeyId = &v
}

func (o TenantIdentityReencryptSecretsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantIdentityReencryptSecretsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RowsExamined) {
		toSerialize["rowsExamined"] = o.RowsExamined
	}
	if !IsNil(o.RowsUpdated) {
		toSerialize["rowsUpdated"] = o.RowsUpdated
	}
	if !IsNil(o.RowsSkippedAllOnTarget) {
		toSerialize["rowsSkippedAllOnTarget"] = o.RowsSkippedAllOnTarget
	}
	if !IsNil(o.FieldsReencrypted) {
		toSerialize["fieldsReencrypted"] = o.FieldsReencrypted
	}
	if !IsNil(o.FieldsSkippedOnTarget) {
		toSerialize["fieldsSkippedOnTarget"] = o.FieldsSkippedOnTarget
	}
	if !IsNil(o.RowsFailed) {
		toSerialize["rowsFailed"] = o.RowsFailed
	}
	if !IsNil(o.Failures) {
		toSerialize["failures"] = o.Failures
	}
	if !IsNil(o.CurrentEncryptionKeyId) {
		toSerialize["currentEncryptionKeyId"] = o.CurrentEncryptionKeyId
	}
	return toSerialize, nil
}

type NullableTenantIdentityReencryptSecretsResponse struct {
	value *TenantIdentityReencryptSecretsResponse
	isSet bool
}

func (v NullableTenantIdentityReencryptSecretsResponse) Get() *TenantIdentityReencryptSecretsResponse {
	return v.value
}

func (v *NullableTenantIdentityReencryptSecretsResponse) Set(val *TenantIdentityReencryptSecretsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantIdentityReencryptSecretsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantIdentityReencryptSecretsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantIdentityReencryptSecretsResponse(val *TenantIdentityReencryptSecretsResponse) *NullableTenantIdentityReencryptSecretsResponse {
	return &NullableTenantIdentityReencryptSecretsResponse{value: val, isSet: true}
}

func (v NullableTenantIdentityReencryptSecretsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantIdentityReencryptSecretsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
