// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the TenantIdentityReencryptFailure type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantIdentityReencryptFailure{}

// TenantIdentityReencryptFailure A single per-field re-wrap failure.
type TenantIdentityReencryptFailure struct {
	// Org whose secret failed to re-wrap.
	OrganizationId *string `json:"organizationId,omitempty"`
	// Name of the field that failed to re-wrap.
	Field *string `json:"field,omitempty"`
	// Error describing why the field could not be re-wrapped.
	Error *string `json:"error,omitempty"`
}

// NewTenantIdentityReencryptFailure instantiates a new TenantIdentityReencryptFailure object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantIdentityReencryptFailure() *TenantIdentityReencryptFailure {
	this := TenantIdentityReencryptFailure{}
	return &this
}

// NewTenantIdentityReencryptFailureWithDefaults instantiates a new TenantIdentityReencryptFailure object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantIdentityReencryptFailureWithDefaults() *TenantIdentityReencryptFailure {
	this := TenantIdentityReencryptFailure{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *TenantIdentityReencryptFailure) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptFailure) GetOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *TenantIdentityReencryptFailure) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *TenantIdentityReencryptFailure) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *TenantIdentityReencryptFailure) GetField() string {
	if o == nil || IsNil(o.Field) {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptFailure) GetFieldOk() (*string, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *TenantIdentityReencryptFailure) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *TenantIdentityReencryptFailure) SetField(v string) {
	o.Field = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *TenantIdentityReencryptFailure) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptFailure) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *TenantIdentityReencryptFailure) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *TenantIdentityReencryptFailure) SetError(v string) {
	o.Error = &v
}

func (o TenantIdentityReencryptFailure) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantIdentityReencryptFailure) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableTenantIdentityReencryptFailure struct {
	value *TenantIdentityReencryptFailure
	isSet bool
}

func (v NullableTenantIdentityReencryptFailure) Get() *TenantIdentityReencryptFailure {
	return v.value
}

func (v *NullableTenantIdentityReencryptFailure) Set(val *TenantIdentityReencryptFailure) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantIdentityReencryptFailure) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantIdentityReencryptFailure) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantIdentityReencryptFailure(val *TenantIdentityReencryptFailure) *NullableTenantIdentityReencryptFailure {
	return &NullableTenantIdentityReencryptFailure{value: val, isSet: true}
}

func (v NullableTenantIdentityReencryptFailure) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantIdentityReencryptFailure) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
