// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
)

// SitePowerProvisioningMode Controls whether power provisioning values are rejected (`disabled`) or managed by a service external to NICo (`external`). Missing or unrecognized stored values are reported and enforced as `disabled`.
type SitePowerProvisioningMode string

// List of SitePowerProvisioningMode
const (
	SITEPOWERPROVISIONINGMODE_DISABLED SitePowerProvisioningMode = "disabled"
	SITEPOWERPROVISIONINGMODE_EXTERNAL SitePowerProvisioningMode = "external"
)

// All allowed values of SitePowerProvisioningMode enum
var AllowedSitePowerProvisioningModeEnumValues = []SitePowerProvisioningMode{
	"disabled",
	"external",
}

func (v *SitePowerProvisioningMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SitePowerProvisioningMode(value)
	for _, existing := range AllowedSitePowerProvisioningModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SitePowerProvisioningMode", value)
}

// NewSitePowerProvisioningModeFromValue returns a pointer to a valid SitePowerProvisioningMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSitePowerProvisioningModeFromValue(v string) (*SitePowerProvisioningMode, error) {
	ev := SitePowerProvisioningMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SitePowerProvisioningMode: valid values are %v", v, AllowedSitePowerProvisioningModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SitePowerProvisioningMode) IsValid() bool {
	for _, existing := range AllowedSitePowerProvisioningModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SitePowerProvisioningMode value
func (v SitePowerProvisioningMode) Ptr() *SitePowerProvisioningMode {
	return &v
}

type NullableSitePowerProvisioningMode struct {
	value *SitePowerProvisioningMode
	isSet bool
}

func (v NullableSitePowerProvisioningMode) Get() *SitePowerProvisioningMode {
	return v.value
}

func (v *NullableSitePowerProvisioningMode) Set(val *SitePowerProvisioningMode) {
	v.value = val
	v.isSet = true
}

func (v NullableSitePowerProvisioningMode) IsSet() bool {
	return v.isSet
}

func (v *NullableSitePowerProvisioningMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSitePowerProvisioningMode(val *SitePowerProvisioningMode) *NullableSitePowerProvisioningMode {
	return &NullableSitePowerProvisioningMode{value: val, isSet: true}
}

func (v NullableSitePowerProvisioningMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSitePowerProvisioningMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
