// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the TenantIdentityReencryptSecretsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantIdentityReencryptSecretsRequest{}

// TenantIdentityReencryptSecretsRequest Request to re-wrap stored tenant identity secrets with the Site's current master encryption key (KEK rotation).
type TenantIdentityReencryptSecretsRequest struct {
	// If set, this identifies a tenant organization that must have an allocation and tenant identity configuration on the Site; only that organization's secrets are re-wrapped. The URL `{org}` separately identifies the provider authorizing the operation. If omitted, every row in the Site's tenant identity store is processed.
	OrganizationId *string `json:"organizationId,omitempty"`
	// When true, decrypt and validate only; no changes are written.
	DryRun *bool `json:"dryRun,omitempty"`
}

// NewTenantIdentityReencryptSecretsRequest instantiates a new TenantIdentityReencryptSecretsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantIdentityReencryptSecretsRequest() *TenantIdentityReencryptSecretsRequest {
	this := TenantIdentityReencryptSecretsRequest{}
	var dryRun bool = false
	this.DryRun = &dryRun
	return &this
}

// NewTenantIdentityReencryptSecretsRequestWithDefaults instantiates a new TenantIdentityReencryptSecretsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantIdentityReencryptSecretsRequestWithDefaults() *TenantIdentityReencryptSecretsRequest {
	this := TenantIdentityReencryptSecretsRequest{}
	var dryRun bool = false
	this.DryRun = &dryRun
	return &this
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *TenantIdentityReencryptSecretsRequest) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsRequest) GetOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *TenantIdentityReencryptSecretsRequest) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *TenantIdentityReencryptSecretsRequest) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetDryRun returns the DryRun field value if set, zero value otherwise.
func (o *TenantIdentityReencryptSecretsRequest) GetDryRun() bool {
	if o == nil || IsNil(o.DryRun) {
		var ret bool
		return ret
	}
	return *o.DryRun
}

// GetDryRunOk returns a tuple with the DryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsRequest) GetDryRunOk() (*bool, bool) {
	if o == nil || IsNil(o.DryRun) {
		return nil, false
	}
	return o.DryRun, true
}

// HasDryRun returns a boolean if a field has been set.
func (o *TenantIdentityReencryptSecretsRequest) HasDryRun() bool {
	if o != nil && !IsNil(o.DryRun) {
		return true
	}

	return false
}

// SetDryRun gets a reference to the given bool and assigns it to the DryRun field.
func (o *TenantIdentityReencryptSecretsRequest) SetDryRun(v bool) {
	o.DryRun = &v
}

func (o TenantIdentityReencryptSecretsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantIdentityReencryptSecretsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if !IsNil(o.DryRun) {
		toSerialize["dryRun"] = o.DryRun
	}
	return toSerialize, nil
}

type NullableTenantIdentityReencryptSecretsRequest struct {
	value *TenantIdentityReencryptSecretsRequest
	isSet bool
}

func (v NullableTenantIdentityReencryptSecretsRequest) Get() *TenantIdentityReencryptSecretsRequest {
	return v.value
}

func (v *NullableTenantIdentityReencryptSecretsRequest) Set(val *TenantIdentityReencryptSecretsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantIdentityReencryptSecretsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantIdentityReencryptSecretsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantIdentityReencryptSecretsRequest(val *TenantIdentityReencryptSecretsRequest) *NullableTenantIdentityReencryptSecretsRequest {
	return &NullableTenantIdentityReencryptSecretsRequest{value: val, isSet: true}
}

func (v NullableTenantIdentityReencryptSecretsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantIdentityReencryptSecretsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
